### ISSUE TITLE
chatkit getUsers method throw 500 server error when user not available

### ISSUE THREAD

**Issue by hossammohammed72** [pusher/chatkit-server-php#52] opened 2019-05-28 16:22 UTC
I was trying to use the method
$chatkit->getUsers();
to check if users existed or not. when users doen't exist it throws out 500 server error, I think it can just return an empty array that would be much better. you're doing a great work keep it up

**Comment by jonathanlloyd** [comment] 2019-08-07 15:24
Hi! Thanks for the bug report - I can't seem to reproduce this with the latest version of the SDK (I get an empty array) - is this still an issue for you?

**Comment by irvine48** [comment] 2020-01-17 14:29
how to i process this message when user not available 
Throw error 404
"The requested user does not exist"

```
Chatkit \ Exceptions \ ChatkitException (404)
The requested user does not exist
```

**Comment by jonathanlloyd** [comment] 2020-03-06 12:48
> how to i process this message when user not available
> Throw error 404
> "The requested user does not exist"
> 
> ```
> Chatkit \ Exceptions \ ChatkitException (404)
> The requested user does not exist
> ```

Hey! Thanks for the feedback could you send more details about your use case to support@pusher.com? Thanks!

**Comment by jonathanlloyd** [comment] 2020-03-06 12:48
Cannot reproduce in the latest version - closing

**Closed as completed by jonathanlloyd** 2020-03-06 12:48 UTC
